import React, { useMemo, useState } from 'react';
import { useBPOState } from '../hooks/useBPOState';
import { SupportTicketPriority, SupportTicketStatus } from '../types';
import { uploadSupportAttachment } from '../services/fileUpload';
import { AlertCircle, CheckCircle2, Clock3, FileText, Inbox, MessageSquare, Paperclip, Send, X } from 'lucide-react';

const STATUS_LABELS = { ABERTO: 'Aberto', EM_ATENDIMENTO: 'Em atendimento', AGUARDANDO_SOLICITANTE: 'Aguardando solicitante', RESOLVIDO: 'Resolvido', ENCERRADO: 'Encerrado' };

export default function ServiceDeskView() {
  const { currentUser, users, companies, supportTickets, addSupportMessage, updateSupportTicket, isUserOnline } = useBPOState();
  const [statusFilter, setStatusFilter] = useState<'ALL' | SupportTicketStatus>('ALL');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [message, setMessage] = useState('');
  const [attachment, setAttachment] = useState<File | null>(null);
  const [sending, setSending] = useState(false);
  const [sendError, setSendError] = useState('');
  const tickets = useMemo(() => supportTickets.filter(ticket => statusFilter === 'ALL' || ticket.status === statusFilter), [statusFilter, supportTickets]);
  const selected = tickets.find(ticket => ticket.id === selectedId) || tickets[0];
  const bpoUsers = users.filter(user => ['BPO_ADMIN', 'BPO_TEAM'].includes(user.role));

  if (currentUser.role !== 'BPO_ADMIN') return <div className="p-8 bg-white border rounded-xl text-center text-xs text-zinc-500">Acesso exclusivo do Administrador BPO.</div>;
  const send = async (event: React.FormEvent) => { event.preventDefault(); if (!selected || (!message.trim() && !attachment) || sending) return; setSending(true); setSendError(''); try { const attachments = attachment ? [await uploadSupportAttachment(attachment)] : []; addSupportMessage(selected.id, message, attachments); setMessage(''); setAttachment(null); } catch (reason) { setSendError(reason instanceof Error ? reason.message : 'Falha ao enviar.'); } finally { setSending(false); } };
  const count = (statuses: SupportTicketStatus[]) => supportTickets.filter(ticket => statuses.includes(ticket.status)).length;

  return <div className="space-y-6">
    <div><h2 className="text-xl font-bold text-zinc-900">Central de Requerimentos</h2><p className="text-xs text-zinc-500 mt-1">Monitore, atribua e responda solicitações de clientes e contadores.</p></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[
      ['Novos', count(['ABERTO']), Inbox, 'text-blue-700 bg-blue-50'], ['Em atendimento', count(['EM_ATENDIMENTO']), Clock3, 'text-amber-700 bg-amber-50'], ['Aguardando cliente', count(['AGUARDANDO_SOLICITANTE']), AlertCircle, 'text-purple-700 bg-purple-50'], ['Concluídos', count(['RESOLVIDO', 'ENCERRADO']), CheckCircle2, 'text-emerald-700 bg-emerald-50']
    ].map(([label, value, Icon, color]) => { const CardIcon = Icon as typeof Inbox; return <div key={String(label)} className="bg-white border border-zinc-200 rounded-xl p-4 flex items-center gap-3"><div className={`p-2 rounded-lg ${color}`}><CardIcon className="h-4 w-4" /></div><div><p className="text-[10px] text-zinc-400 uppercase font-bold">{label as string}</p><p className="text-xl font-black">{value as number}</p></div></div>; })}</div>
    <div className="flex justify-end"><select value={statusFilter} onChange={e => setStatusFilter(e.target.value as typeof statusFilter)} className="border border-zinc-200 bg-white rounded-lg p-2 text-xs"><option value="ALL">Todos os status</option>{Object.entries(STATUS_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div>
    <div className="grid xl:grid-cols-[360px_1fr] gap-5 min-h-[570px]">
      <div className="bg-white border border-zinc-200 rounded-xl overflow-hidden"><div className="p-4 border-b text-xs font-bold">Fila de atendimento ({tickets.length})</div><div className="divide-y max-h-[620px] overflow-y-auto">{tickets.map(ticket => <button key={ticket.id} onClick={() => setSelectedId(ticket.id)} className={`w-full p-4 text-left cursor-pointer ${selected?.id === ticket.id ? 'bg-[#0B2C52]/5 border-l-4 border-[#C8102E]' : 'hover:bg-zinc-50'}`}><div className="flex justify-between"><span className="font-mono text-[10px] text-zinc-400">{ticket.protocol}</span><span className={`text-[9px] font-black ${ticket.priority === 'URGENTE' ? 'text-red-600' : 'text-zinc-500'}`}>{ticket.priority}</span></div><p className="font-bold text-xs mt-1 truncate">{ticket.subject}</p><p className="text-[10px] text-zinc-500 mt-1">{ticket.requesterName} · {companies.find(c => c.id === ticket.companyId)?.tradeName}</p><p className="text-[9px] text-[#0B2C52] font-bold mt-2">{STATUS_LABELS[ticket.status]}</p></button>)}{tickets.length === 0 && <p className="p-8 text-center text-xs text-zinc-400">Fila vazia.</p>}</div></div>
      <div className="bg-white border border-zinc-200 rounded-xl flex flex-col overflow-hidden">{selected ? <><div className="p-5 border-b space-y-4"><div><span className="font-mono text-[10px] text-zinc-400">{selected.protocol}</span><h3 className="font-bold mt-1">{selected.subject}</h3><p className="text-xs text-zinc-500 mt-1 flex items-center gap-1.5">Solicitante: {selected.requesterName}<span className={`h-2 w-2 rounded-full ${isUserOnline(selected.requesterId) ? 'bg-emerald-500 animate-pulse' : 'bg-zinc-300'}`} /><strong className={isUserOnline(selected.requesterId) ? 'text-emerald-700' : 'text-zinc-400'}>{isUserOnline(selected.requesterId) ? 'online' : 'offline'}</strong></p></div><p className="text-xs bg-zinc-50 border border-zinc-100 p-3 rounded-lg whitespace-pre-wrap">{selected.description}</p><div className="grid sm:grid-cols-3 gap-2"><select value={selected.status} onChange={e => updateSupportTicket(selected.id, { status: e.target.value as SupportTicketStatus })} className="border rounded-lg p-2 text-xs">{Object.entries(STATUS_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select value={selected.priority} onChange={e => updateSupportTicket(selected.id, { priority: e.target.value as SupportTicketPriority })} className="border rounded-lg p-2 text-xs"><option value="BAIXA">Prioridade baixa</option><option value="NORMAL">Prioridade normal</option><option value="ALTA">Prioridade alta</option><option value="URGENTE">Prioridade urgente</option></select><select value={selected.assignedToId || ''} onChange={e => updateSupportTicket(selected.id, { assignedToId: e.target.value })} className="border rounded-lg p-2 text-xs"><option value="">Sem responsável</option>{bpoUsers.map(user => <option key={user.id} value={user.id}>{user.name} — {isUserOnline(user.id) ? 'online' : 'offline'}</option>)}</select></div></div>
        <div className="flex-1 p-5 space-y-3 bg-zinc-50 overflow-y-auto max-h-[340px]">{selected.messages.length === 0 && <div className="text-center text-xs text-zinc-400 py-8"><MessageSquare className="h-7 w-7 mx-auto mb-2" />Envie a primeira resposta ao solicitante.</div>}{selected.messages.map(item => { const fromBpo = ['BPO_ADMIN', 'BPO_TEAM'].includes(item.authorRole); return <div key={item.id} className={`flex ${fromBpo ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[80%] px-3 py-2 rounded-xl ${fromBpo ? 'bg-[#0B2C52] text-white' : 'bg-white border'}`}><p className="text-[10px] font-bold opacity-70">{item.authorName}</p>{item.content && <p className="text-xs mt-0.5 whitespace-pre-wrap">{item.content}</p>}{item.attachments?.map(file => <a key={file.id} href={file.url} download={file.name} className={`mt-2 flex items-center gap-2 rounded-lg px-2.5 py-2 text-[10px] font-bold ${fromBpo ? 'bg-white/10 hover:bg-white/20' : 'bg-zinc-50 border hover:bg-zinc-100'}`}><FileText className="h-4 w-4" /><span className="truncate">{file.name}</span></a>)}<p className="text-[9px] opacity-60 mt-1">{new Date(item.createdAt).toLocaleString('pt-BR')}</p></div></div>; })}</div>
        {!['RESOLVIDO', 'ENCERRADO'].includes(selected.status) && <form onSubmit={send} className="p-4 border-t space-y-2">{attachment && <div className="flex justify-between text-[10px] bg-blue-50 border border-blue-100 rounded-lg px-3 py-2"><span className="font-bold truncate">{attachment.name}</span><button type="button" onClick={() => setAttachment(null)}><X className="h-3.5 w-3.5" /></button></div>}{sendError && <p className="text-[10px] text-rose-600">{sendError}</p>}<div className="flex gap-2"><label className="border p-2.5 rounded-lg cursor-pointer" title="Anexar arquivo"><Paperclip className="h-4 w-4" /><input type="file" className="hidden" onChange={event => setAttachment(event.target.files?.[0] || null)} /></label><input value={message} onChange={e => setMessage(e.target.value)} placeholder="Responder ao solicitante..." className="flex-1 border rounded-lg px-3 text-xs" /><button disabled={sending} className="bg-[#C8102E] disabled:opacity-50 text-white p-2.5 rounded-lg cursor-pointer"><Send className="h-4 w-4" /></button></div></form>}</> : <div className="flex-1 flex items-center justify-center text-xs text-zinc-400">Selecione um requerimento da fila.</div>}</div>
    </div>
  </div>;
}
